# Generated by Django 2.1.1 on 2018-10-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour', models.CharField(max_length=200)),
                ('date_of_review', models.DateTimeField(verbose_name='date of review')),
                ('source', models.CharField(max_length=200)),
                ('reviewer_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=5)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
    ]
