# Generated by Django 2.1.1 on 2018-10-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20181016_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='city',
            field=models.CharField(default='Washington DC', max_length=200),
        ),
        migrations.AddField(
            model_name='reviews',
            name='guide',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
