# Generated by Django 2.1.1 on 2018-10-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20181017_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='city',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='guide',
        ),
    ]
