# Generated by Django 2.1.1 on 2018-10-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20181024_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='guide',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
