# Generated by Django 2.1.1 on 2018-10-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_reviews_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='city',
            field=models.CharField(default='Washington DC', max_length=200),
        ),
    ]
