# Generated by Django 2.1.1 on 2018-10-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_reviews_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date_of_review',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
